name: canada_hotels
description: CanadaHotels - Application de réservation d'hôtels de luxe
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  go_router: ^13.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.1.0
  http: ^1.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
